# CEX to use with ccxt, will be used to calc assets prices and refresh, no private api needed.
# "bittrex"  # https://github.com/ccxt/ccxt/blob/master/doc/exchange-markets.rstz

ccxt_exchange: binance
ccxt_hostname: None  # "global.bittrex.com"  # CUSTOM CCXT HOSTNAME, SET TO None TO USE DEFAULT
debug_level: 2
